services:
  frontend:
    container_name: ${COMPOSE_PROJECT_NAME}-frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    command: serve
    env_file:
      - .env
  caddy:
    container_name: ${COMPOSE_PROJECT_NAME}-caddy
    restart: unless-stopped
    image: caddy:2.7.6
    env_file:
      - .env
    ports:
      - '${SERVICE_PORT_HTTPS:-443}:443'
      - '${SERVICE_PORT_HTTP:-80}:80'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
volumes:
  caddy_data:
  caddy_config:
