services:
  homepage:
    container_name: homepage
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: serve
    env_file:
      - .env
    ports:
      - '${SERVICE_PORT}:3000'
