export const sebnSkills: string[] = [
  'PhP',
  'Laravel',
  'JS',
  'CSS',
  'HTML',
  'DHCP',
  'Active directory',
  'Ngnix',
  'docker',
  'Mysql',
  'Git',
  'Linux',
  'Python',
  'Django',
  'Drf',
  'Celery',
  'React',
  'Redux',
  'Material UI',
];
export const coaxSkills: string[] = [
  'fastapi',
  'mongodb',
  'postgresql',
  'redis',
  'pandas',
  'numpy',
  'drf spectacular',
  'mermaid js',
  'figma',
  'mailjet',
  'load-testing',
  'locust',
  'unit-testing',
  'pytest',
  'yahoofinance api',
  'facebook api',
  'instagram api',
  'pinterest api',
  'google translate api',
  'google calendar api',
  'google merchant api',
  'twilio',
  'jira',
  'pre-commit',
  'ruff',
  'aws:s3',
  'aws:lambda',
  'aws:ec2',
  'aws:rds',
  'aws:sqs',
  'aws:sns',
  'elasticsearch',
];

export const planeksSkills: string[] = [
  'selenium',
  'caddy',
  'digital ocean',
  'htmx',
  'hyperscript',
  'oauth2',
  'office 365 api',
  'bootstrap',
  'mantine ui',
  'trello',
];
