type skill = {
  icon?: string;
  label: string;
  adopted?: Date;
};

export const sebnSkills: skill[] = [
  { icon: 'php', label: 'PhP' },
  { icon: 'laravel', label: 'Laravel' },
  { icon: 'javascript', label: 'JS' },
  { icon: 'css3', label: 'CSS' },
  { icon: 'html5', label: 'HTML' },
  { label: 'DHCP' },
  { label: 'Active Directory' },
  { icon: 'nginx', label: 'Nginx' },
  { label: 'Docker' },
  { icon: 'mysql', label: 'MySQL' },
  { icon: 'mariadb', label: 'MariaDB' },
  { icon: 'stripe', label: 'Stripe' },
  { icon: 'linux', label: 'Linux' },
  { icon: 'debian', label: 'Debian' },
  { icon: 'python', label: 'Python' },
  { icon: 'django', label: 'Django' },
  { label: 'DRF' },
  { icon: 'celery', label: 'Celery' },
  { icon: 'react', label: 'React' },
  { icon: 'vite', label: 'Vite' },
  { icon: 'reactrouter', label: 'React Router' },
  { icon: 'redux', label: 'Redux' },
  { icon: 'mui', label: 'Material UI' },
];

export const coaxSkills: skill[] = [
  { icon: 'fastapi', label: 'FastAPI' },
  { icon: 'pydantic', label: 'Pydantic' },
  { icon: 'mongodb', label: 'MongoDB' },
  { icon: 'postgresql', label: 'PostgreSQL' },
  { icon: 'sentry', label: 'Sentry' },
  { icon: 'redis', label: 'Redis' },
  { icon: 'pandas', label: 'Pandas' },
  { icon: 'numpy', label: 'NumPy' },
  { icon: 'swagger', label: 'DRF Spectacular' },
  { icon: 'typescript', label: 'TypeScript' },
  { icon: 'mermaid', label: 'Mermaid JS' },
  { label: 'Mailjet' },
  { icon: 'mailgun', label: 'Mailgun' },
  { icon: 'openai', label: 'OpenAI api' },
  { label: 'Load Testing' },
  { label: 'Locust' },
  { label: 'Unit Testing' },
  { icon: 'pytest', label: 'Pytest' },
  { label: 'Yahoo Finance API' },
  { icon: 'shopify', label: 'Shopify API' },
  { icon: 'facebook', label: 'Facebook API' },
  { icon: 'instagram', label: 'Instagram API' },
  { icon: 'pinterest', label: 'Pinterest API' },
  { icon: 'googletranslate', label: 'Google Translate API' },
  { icon: 'googlecalendar', label: 'Google Calendar API' },
  { label: 'Google Merchant API' },
  { icon: 'twilio', label: 'Twilio' },
  { icon: 'paypal', label: 'PayPal' },
  { icon: 'algolia', label: 'Algolia' },
  { icon: 'jira', label: 'Jira' },
  { icon: 'precommit', label: 'Pre-commit' },
  { icon: 'ruff', label: 'Ruff' },
  { icon: 'amazons3', label: 'AWS S3' },
  { icon: 'awslambda', label: 'AWS Lambda' },
  { icon: 'amazonec2', label: 'AWS EC2' },
  { icon: 'amazonrds', label: 'AWS RDS' },
  { icon: 'amazonsqs', label: 'AWS SQS' },
  { icon: 'antdesign', label: 'Ant Design' },
  { label: 'AWS SNS' },
  { icon: 'amazonelasticache', label: 'AWS ElastiCache' },
  { icon: 'elasticsearch', label: 'Elasticsearch' },
];

export const planeksSkills: skill[] = [
  { icon: 'selenium', label: 'Selenium' },
  { icon: 'netdata', label: 'Netdata' },
  { icon: 'caddy', label: 'Caddy' },
  { icon: 'letsencrypt', label: "Let's Encrypt" },
  { icon: 'digitalocean', label: 'Digital Ocean' },
  { icon: 'nextdotjs', label: 'NextJS' },
  { icon: 'minio', label: 'MinIO' },
  { icon: 'htmx', label: 'HTMX' },
  { label: 'Hyperscript' },
  { label: 'OAuth2' },
  { label: 'Office 365 API' },
  { icon: 'bootstrap', label: 'Bootstrap' },
  { icon: 'mantine', label: 'Mantine UI' },
  { icon: 'trello', label: 'Trello' },
];

export const tools: skill[] = [
  { icon: 'git', label: 'Git' },
  { icon: 'github', label: 'GitHub' },
  { icon: 'dbeaver', label: 'DBeaver' },
  { icon: 'docker', label: 'Docker' },
  { label: 'VS Code' },
  { label: 'NPM' },
  { icon: 'yarn', label: 'Yarn' },
  { icon: 'poetry', label: 'Poetry' },
  { label: 'Pyenv' },
  { icon: 'hoppscotch', label: 'Hoppscotch' },
  { icon: 'nvm', label: 'NVM' },
  { icon: 'warp', label: 'Warp' },
  { icon: 'figma', label: 'Figma' },
  { icon: 'macos', label: 'MacOS' },
  { icon: 'obsidian', label: 'Obsidian' },
];

export const domains: string[] = [
  'Healthcare',
  'Fintech',
  'E-commerce',
  'Automotive',
  'Manufacturing',
  'Logistics',
  'Telecom',
  'Real Estate',
];
